import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`max-w-screen-2xl min-h-screen bg-green-500 ${inter.className}`}>
        <div className=" bg-red-500 my-20">
        <Navbar />
        <main className="my-20 bg-red-300 m-2 rounded-lg">{children}</main>
        <Footer />
        </div>
      </body>
    </html>
  );
}
